//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credible_Dev_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_course_portal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_course_portal()
        {
            this.u_registration = new HashSet<u_registration>();
        }
    
        public int course_portal_id { get; set; }
        public int portal_id { get; set; }
        public int course_variant_id { get; set; }
        public string credit_type_cd { get; set; }
        public string credit_type_nm { get; set; }
        public decimal earned_credit { get; set; }
        public string syllabus { get; set; }
        public string syllabus_url { get; set; }
        public decimal regular_px { get; set; }
        public Nullable<decimal> sale_px { get; set; }
        public decimal sort_order { get; set; }
        public bool forum_ind { get; set; }
        public int classroom_sz { get; set; }
        public Nullable<int> forum_posts_per_topic { get; set; }
        public System.DateTime display_start_dt { get; set; }
        public System.DateTime display_finish_dt { get; set; }
        public System.DateTime purchase_start_dt { get; set; }
        public System.DateTime purchase_finish_dt { get; set; }
        public System.DateTime access_start_dt { get; set; }
        public Nullable<System.DateTime> access_finish_dt { get; set; }
        public Nullable<int> access_day { get; set; }
        public bool active_ind { get; set; }
        public System.DateTime created_dttm { get; set; }
        public int created_id { get; set; }
        public Nullable<System.DateTime> modified_dttm { get; set; }
        public Nullable<int> modified_id { get; set; }
        public int grade_id { get; set; }
        public string deployment_status { get; set; }
        public Nullable<int> reg_method { get; set; }
        public string course_portal_nm { get; set; }
        public bool self_reg_enabled_ind { get; set; }
        public string course_display_nm { get; set; }
        public string course_display_img { get; set; }
        public string course_subject { get; set; }
        public string course_topic { get; set; }
        public string course_default_standard { get; set; }
        public Nullable<bool> credit_upgrade_ind { get; set; }
        public Nullable<decimal> upgrade_price { get; set; }
        public string upgrade_overview { get; set; }
        public bool enable_evidence { get; set; }
        public string credit_acceptance { get; set; }
        public int clustered_id { get; set; }
    
        public virtual u_portal u_portal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_registration> u_registration { get; set; }
    }
}
