//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credible_Dev_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_portal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_portal()
        {
            this.u_course_portal = new HashSet<u_course_portal>();
        }
    
        public int portal_id { get; set; }
        public string portal_nm { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> agency_id { get; set; }
        public Nullable<int> school_id { get; set; }
        public int portal_type_id { get; set; }
        public bool marketing_partner_ind { get; set; }
        public bool credit_grantor_ind { get; set; }
        public Nullable<int> other_credit_grantor_id { get; set; }
        public bool direct_buyer_ind { get; set; }
        public string notes { get; set; }
        public System.DateTime display_start_dt { get; set; }
        public System.DateTime display_finish_dt { get; set; }
        public System.DateTime purchase_start_dt { get; set; }
        public System.DateTime purchase_finish_dt { get; set; }
        public System.DateTime access_start_dt { get; set; }
        public Nullable<System.DateTime> access_finish_dt { get; set; }
        public Nullable<int> access_day { get; set; }
        public string title { get; set; }
        public string keyword { get; set; }
        public string description { get; set; }
        public string introduction { get; set; }
        public string promotion { get; set; }
        public string data { get; set; }
        public string completion { get; set; }
        public string flyer_url { get; set; }
        public string logo_url { get; set; }
        public string logo { get; set; }
        public string contact_email { get; set; }
        public bool active_ind { get; set; }
        public System.DateTime created_dttm { get; set; }
        public int created_id { get; set; }
        public Nullable<System.DateTime> modified_dttm { get; set; }
        public Nullable<int> modified_id { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string theme { get; set; }
        public string login_page_logo { get; set; }
        public string login_page_text { get; set; }
        public Nullable<bool> special_use { get; set; }
        public bool self_reg_ind { get; set; }
        public Nullable<bool> self_reg_limit_by_teacher { get; set; }
        public string eClassroom_logo { get; set; }
        public Nullable<int> self_reg_teacher_course_limit { get; set; }
        public bool chat_ind { get; set; }
        public bool pwd_change_rqd_ind { get; set; }
        public bool review_mode_ind { get; set; }
        public Nullable<bool> only_grade_complete_ind { get; set; }
        public int clustered_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_course_portal> u_course_portal { get; set; }
    }
}
