//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credible_Dev_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_registration
    {
        public int registration_id { get; set; }
        public Nullable<int> order_detail_id { get; set; }
        public int user_id { get; set; }
        public int course_portal_id { get; set; }
        public System.DateTime registration_dttm { get; set; }
        public string registration_type_cd { get; set; }
        public Nullable<System.DateTime> drop_out_dttm { get; set; }
        public System.DateTime access_start_dt { get; set; }
        public System.DateTime access_finish_dt { get; set; }
        public bool active_ind { get; set; }
        public System.DateTime created_dttm { get; set; }
        public int created_id { get; set; }
        public Nullable<System.DateTime> modified_dttm { get; set; }
        public Nullable<int> modified_id { get; set; }
        public Nullable<System.DateTime> complete_dttm { get; set; }
        public Nullable<decimal> final_grade { get; set; }
        public Nullable<int> course_portal_self_reg_id { get; set; }
        public Nullable<bool> credit_upgrade_ind { get; set; }
        public bool withdrawn_ind { get; set; }
        public Nullable<int> grade_id { get; set; }
        public int enrollment_status_id { get; set; }
        public Nullable<System.DateTime> last_activity_date { get; set; }
        public int clustered_id { get; set; }
    
        public virtual u_course_portal u_course_portal { get; set; }
        public virtual u_user u_user { get; set; }
    }
}
