//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credible_Dev_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_user()
        {
            this.u_registration = new HashSet<u_registration>();
        }
    
        public int user_id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<int> client_id { get; set; }
        public string company_nm { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string first_nm { get; set; }
        public string last_nm { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public Nullable<int> county_id { get; set; }
        public string state { get; set; }
        public string postal_cd { get; set; }
        public string sec_address1 { get; set; }
        public string sec_address2 { get; set; }
        public string sec_city { get; set; }
        public string sec_state { get; set; }
        public string sec_postal_cd { get; set; }
        public bool speaker_ind { get; set; }
        public bool marketing_partner_ind { get; set; }
        public bool credit_grantor_ind { get; set; }
        public bool direct_buyer_ind { get; set; }
        public bool active_ind { get; set; }
        public System.DateTime created_dttm { get; set; }
        public int created_id { get; set; }
        public Nullable<System.DateTime> modified_dttm { get; set; }
        public Nullable<int> modified_id { get; set; }
        public bool notification_email_ind { get; set; }
        public Nullable<int> subject_id { get; set; }
        public Nullable<int> grade_level_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public bool temp_pwd_changed { get; set; }
        public Nullable<System.DateTime> user_agreement_accept_dttm { get; set; }
        public string district_employee_id { get; set; }
        public string state_employee_id { get; set; }
        public string group_nm { get; set; }
        public bool review_mode_ind { get; set; }
        public bool chat_ind { get; set; }
        public string soc_sec_nmb { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string avatar_url { get; set; }
        public string thumbnail_url { get; set; }
        public int clustered_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_registration> u_registration { get; set; }
    }
}
